substitutions:
  node_name: crowpanel
  friendly_node_name: CrowPanel
  timezone: Europe/Stockholm

logger:
  level: VERY_VERBOSE

packages:
  common: !include ../esphome-common/common/common_eink.yaml
  hardware: !include ../esphome-common/hardware/esp32/crowpanel-4.2.yaml
  pages: !include crowpanel_pages.yaml

external_components:
  - source:
      type: local
      path: components
    components: [crowpanel_epaper, page]

globals:
  - id: first_render
    type: bool
    restore_value: false
    initial_value: 'true'

binary_sensor:
  - id: !extend btn_menu
    filters:
      - delayed_on: 100ms
    on_press:
      - lvgl.page.next:
          animation: NONE

  - id: !extend btn_exit
    filters:
      - delayed_on: 100ms
    on_press:
      - lvgl.page.previous:
          animation: NONE

  - id: !extend btn_confirm
    on_press:
      - lambda: 'auto* fp = esphome::page::Page::active; if (fp) fp->on_confirm();'

  - id: !extend btn_rotary_up
    on_press:
      - lambda: 'auto* fp = esphome::page::Page::active; if (fp) fp->on_up();'

  - id: !extend btn_rotary_down
    on_press:
      - lambda: 'auto* fp = esphome::page::Page::active; if (fp) fp->on_down();'


sensor:
  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.shellypro3em_3ce90e6eaa68_temperature
    on_value:
      - lvgl.label.update:
          id: lbl_outdoor_temp
          text: !lambda 'return str_sprintf("Shelly: %.1f °C", x).c_str();'

font:
  - file: apps/dashboard/fonts/GothamRnd-Bold.ttf
    id: font_large
    size: 28
    bpp: 1
  - file: apps/dashboard/fonts/GothamRnd-Bold.ttf
    id: font_medium
    size: 22
    bpp: 1
  - file: apps/dashboard/fonts/GothamRnd-Book.ttf
    id: font_small
    size: 18
    bpp: 1

lvgl:
  displays: epd
  buffer_size: 25%
  color_depth: 16
  rotation: 180
  anim_time: 0ms
  theme:
    button:
      bg_opa: TRANSP
      border_width: 0
      radius: 0
      text_color: 0x000000
      text_font: font_large
      focused:
        bg_color: 0x000000
        bg_opa: COVER
        text_color: 0xFFFFFF
        border_color: 0x000000
    label:
      text_color: 0x000000
      bg_opa: TRANSP
    spinbox:
      bg_color: 0xFFFFFF
      bg_opa: COVER
      border_width: 2
      border_color: 0x000000
      radius: 0
      text_color: 0x000000
      text_font: font_large
      focused:
        border_color: 0x000000
        border_width: 2
        radius: 0
      selected:
        bg_color: 0x000000
        bg_opa: COVER
        text_color: 0xFFFFFF
  encoders:
    - id: main_encoder
      enter_button: btn_confirm
      sensor:
        left_button: btn_rotary_up
        right_button: btn_rotary_down
      group: actions_group
  on_draw_end:
    - lambda: |
        if (id(first_render)) {
          id(epd).force_full_update();
          id(first_render) = false;
        }
    - component.update: epd
  pages:
    - !include crowpanel_pages/home.yaml
    - !include crowpanel_pages/climate.yaml
