substitutions:
  node_name: crowpanel
  friendly_node_name: CrowPanel
  timezone: Europe/Stockholm
  page_font: font_large
  eink_display: epd
  eink_buffer_size: 25%
  eink_btn_next: btn_menu
  eink_btn_prev: btn_exit
  eink_btn_confirm: btn_confirm
  eink_btn_up: btn_rotary_up
  eink_btn_down: btn_rotary_down

logger:
  level: VERY_VERBOSE

packages:
  common: !include ../esphome-common/common/common_eink.yaml
  hardware: !include ../esphome-common/hardware/esp32/crowpanel-4.2.yaml
  eink_hw: !include ../esphome-eink-ui/config/lvgl_eink.yaml
  eink_fonts: !include ../esphome-eink-ui/config/fonts.yaml
  eink_theme: !include ../esphome-eink-ui/config/eink_theme.yaml

page:
  - !include crowpanel_pages/home.yaml
  - !include crowpanel_pages/actions.yaml
  - !include crowpanel_pages/poolpump.yaml
  - !include crowpanel_pages/power.yaml
  - !include crowpanel_pages/settings.yaml

external_components:
  - source:
      type: local
      path: ../esphome-eink-ui/components
    components: [page]

