esphome:
  name: ${node_name}
  friendly_name: ${friendly_node_name}
  build_path: ./build/${node_name}

esp8266:
  board: esp01_1m
  early_pin_init: False

binary_sensor:
  - platform: gpio
    name: "Button 1"
    id: "button_1"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_1"
  - platform: gpio
    name: "Button 2"
    id: "button_2"
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_2"
  - platform: gpio
    name: "Button 3"
    id: "button_3"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_3"
  - platform: gpio
    name: "Button 4"
    id: "button_4"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    on_press:
    - switch.toggle: "relay_4"

switch:
  - platform: gpio
    name: "Relay 1"
    id: "relay_1"        
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO12
  - platform: gpio
    name: "Relay 2"
    id: "relay_2"
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO5
  - platform: gpio
    name: "Relay 3"
    id: "relay_3"
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO4
  - platform: gpio
    name: "Relay 4"
    restore_mode: RESTORE_DEFAULT_OFF
    id: "relay_4"
    pin: GPIO15

status_led:
  pin:
    number: GPIO13
    inverted: True