sensor:
  - platform: homeassistant
    id: ha_pump_on_hour
    entity_id: ${entity_on_hour}
    on_value:
      - lambda: |
          if (id(${input_on_hour})) id(${input_on_hour})->on_ha_update(x);
  - platform: homeassistant
    id: ha_pump_on_min
    entity_id: ${entity_on_min}
    on_value:
      - lambda: |
          if (id(${input_on_min})) id(${input_on_min})->on_ha_update(x);
  - platform: homeassistant
    id: ha_pump_off_hour
    entity_id: ${entity_off_hour}
    on_value:
      - lambda: |
          if (id(${input_off_hour})) id(${input_off_hour})->on_ha_update(x);
  - platform: homeassistant
    id: ha_pump_off_min
    entity_id: ${entity_off_min}
    on_value:
      - lambda: |
          if (id(${input_off_min})) id(${input_off_min})->on_ha_update(x);

binary_sensor:
  - platform: homeassistant
    id: ha_pump_enable
    entity_id: ${entity_enable}
    on_state:
      - lambda: |
          if (id(${input_enable})) id(${input_enable})->on_ha_state(x);
