# WiFi Configuration
# Primary, Secondary and Fallback SSIDs
#
# URL: https://esphome.io/components/wifi.html
# URL: https://esphome.io/components/captive_portal.html
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_sec
      password: !secret wifi_password_sec

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_node_name} Fallback"
    password: !secret wifi_fallback_password

captive_portal:
