# Time Synchronization Configuration
# Using SNTP Time Source
#
# URL: https://esphome.io/components/time/sntp.html
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Mexico_City
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org