# Include common stuff
packages:
  common: !include ../common/common.yaml
  hardware: !include ../hardware/esp8266/sonoff-basic-r2.yaml

esphome:
  includes: apps/poolpump/scheduler.h

# Check the schedule every minute
time:
  - platform: sntp
    id: !extend sntp_time
    on_time:
      - minutes: /1
        seconds: 0
        then:
          - lambda: |-
              // Check if the time is valid and that the user enabled this automation
              if (id(sntp_time).now().is_valid() && id(pump_enable).state) {
                PoolPump::check_schedule(id(sntp_time), id(pump_on_hour), id(pump_on_min), id(pump_off_hour), id(pump_off_min), id(relay));
              }

number:
  - platform: template
    name: "Pump on hour"
    id: pump_on_hour
    icon: "mdi:clock-time-three-outline"
    unit_of_measurement: "h"
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    initial_value: 0
    restore_value: true

  - platform: template
    name: "Pump on minute"
    id: pump_on_min
    icon: "mdi:clock-time-three-outline"
    unit_of_measurement: "m"
    optimistic: true
    min_value: 0
    max_value: 59
    step: 1
    initial_value: 0
    restore_value: true

  - platform: template
    name: "Pump off hour"
    id: pump_off_hour
    icon: "mdi:clock-time-three-outline"
    unit_of_measurement: "h"
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    initial_value: 0
    restore_value: true

  - platform: template
    name: "Pump off minute"
    id: pump_off_min
    icon: "mdi:clock-time-three-outline"
    unit_of_measurement: "m"
    optimistic: true
    min_value: 0
    max_value: 59
    step: 1
    initial_value: 0
    restore_value: true

switch:
  - platform: template
    name: "Pump Enable"
    id: pump_enable
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF 